test notarize -2

diff --git a/.github/workflows/build_release.yml b/.github/workflows/build_release.yml
--- a/.github/workflows/build_release.yml
+++ b/.github/workflows/build_release.yml
@@ -147,6 +147,19 @@ jobs:
           APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
           APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
         run: |
+          set -E
+          set -o functrace
+          function handle_error {
+              local retval=$?
+              local line=${last_lineno:-$1}
+              echo "Failed at $line: $BASH_COMMAND"
+              echo "Trace: " "$@"
+              exit $retval
+          }
+          if (( ${BASH_VERSION%%.*} <= 3 )) || [[ ${BASH_VERSION%.*} = 4.0 ]]; then
+                  trap '[[ $FUNCNAME = handle_error ]] || { last_lineno=$real_lineno; real_lineno=$LINENO; }' DEBUG
+          fi
+          trap 'handle_error $LINENO ${BASH_LINENO[@]}' ERR
           # Keychain Setup
           export KEYCHAIN_PATH=$RUNNER_TEMP/notarization.keychain-db
           export APPLE_API_KEY="${{ runner.temp }}/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8"
@@ -161,8 +174,8 @@ jobs:
           security set-keychain-settings -lt 3600 -u ${KEYCHAIN_PATH}
 
           # Import Application Certificate
-          #CSC_LINK="${{ secrets.APPLE_MAC_CERT }}"
-          #CSC_KEY_PASSWORD="${{ secrets.APPLE_CERT_PASSWORD }}"
+          # CSC_LINK="${{ secrets.APPLE_MAC_CERT }}"
+          # CSC_KEY_PASSWORD="${{ secrets.APPLE_CERT_PASSWORD }}"
           echo -n "${{ secrets.APPLE_MAC_CERT }}" | base64 --decode -o "${{ runner.temp }}/app_cert.p12"
           security import "${{ runner.temp }}/app_cert.p12" \
             -P "${{ secrets.APPLE_CERT_PASSWORD }}" \
